kind: pipeline
type: docker
name: server

steps:
  - name: test
    image: node:12.16.3
    commands:
      - npm install --production
      - npm test

---
kind: pipeline
type: docker
name: client

steps:
  - name: build
    image: node:12.16.3
    commands:
      - cd client && npm install --production
      - npm run build
      - npm run test
